CREATE TABLE app_configs (
  config_key VARCHAR(128) NOT NULL PRIMARY KEY,
  config_value TEXT NOT NULL,
  description TEXT NULL,
  public BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
